#1097 tel URL scheme
ExpressionEngine/ExpressionEngine pull request #1124
Opened 2021-06-04 18:39 UTC by dougblackjr

## Overview

Adds `tel` scheme option to URL fieldtype.

Resolves [#1097]https://github.com/ExpressionEngine/ExpressionEngine/issues/1097).

## Nature of This Change

- [ ] 🐛 Fixes a bug
- [X] 🚀 Implements a new feature
- [X] 🛁 Refactors existing code
- [X] 💅 Fixes coding style
- [ ] ✅ Adds tests
- [ ] 👽 Adds new dependency
- [ ] 🔥 Removes unused files / code
- [ ] 🔒 Improves security 

## Is this backwards compatible?

- [X] Yes
- [ ] No

## Documentation
User Guide Pull Request: https://github.com/ExpressionEngine/ExpressionEngine-User-Guide/pull/193

2021-06-24 15:10 UTC, intoeetive approved these changes

2021-06-24 15:18 UTC, intoeetive requested changes

2021-06-24 15:18 UTC, intoeetive commented on system/ee/ExpressionEngine/Addons/url/ft.url.php
> +            if (in_array('//', $this->get_setting('allowed_url_schemes'))
@dougblackjr looks like this is breaking PSR rule:
> The first expression of a multi-line control structure must be on the line after the opening parenthesis

Can you please fix this as well as resolve the conflict with changelog file

2021-06-24 15:18 UTC, intoeetive commented on system/ee/ExpressionEngine/Addons/url/ft.url.php
> +            if (isset($parsed_url['scheme'], $parsed_url['path']) &&
same issue as above

2021-06-29 19:21 UTC, obfuscode approved these changes

2021-06-29 19:22 UTC, merged