Add extra parameters to `exp:channel:category_archive`
ExpressionEngine/ExpressionEngine pull request #1257
Opened 2021-08-06 22:00 UTC by robsonsobral

## Overview

Add `sticky` parameter and `most_used_categories` value to `order_by` parameter to `exp:channel:category_archive`.

Resolves [#1256](https://github.com/ExpressionEngine/ExpressionEngine/issues/1256).

## Nature of This Change

- [ ] 🐛 Fixes a bug
- [x] 🚀 Implements a new feature
- [ ] 🛁 Refactors existing code
- [ ] 💅 Fixes coding style
- [ ] ✅ Adds tests
- [ ] 👽 Adds new dependency
- [ ] 🔥 Removes unused files / code
- [ ] 🔒 Improves security 

## Is this backwards compatible?

- [x] Yes
- [ ] No

## Documentation

User Guide Pull Request: https://github.com/ExpressionEngine/ExpressionEngine-User-Guide/pulls/NNN

2021-10-13 11:27 UTC, intoeetive requested changes
I think it would be good to add support for other options, that we have with channel entries, for consistency
`sticky="yes"`
`sticky="no"`
`sticky="only"`
https://docs.expressionengine.com/latest/channels/entries.html#sticky

2021-10-20 00:30 UTC, robsonsobral commented
@intoeetive , being `no` the default value of `sticky`, what else do I need to add?! `yes` and `only` are already there. 😕

2021-10-20 05:50 UTC, intoeetive commented
You are absolutely right. Not sure how I missed that =(

I'll add some tests to it and then we'll bake it into some future release (likely 6.2.0)

Thank you very much!

2021-11-16 11:42 UTC, intoeetive commented
@robsonsobral I have added tests around `orderby="most_used_categories"` (did not add any for sticky parameter yet) and it looks like those are failing.
Can you have a look and fix? Or just remove this feature if this PR is mostly about `sticky` parameter (which still needs tests)

2021-11-16 15:46 UTC, robsonsobral commented
I've no idea which drug I used when I coded that. That query makes no sense. I gonna remove `most_used_categories`.

2021-12-06 21:07 UTC, TomJaeger commented on tests/cypress/support/templates/cats.group/archive-sorted.html
> +    {exp:channel:category_archive channel="about" style="linear" orderby="title"}
Other then the div class name above.. I don't see a difference between this and whats on line 17... Should this be running a different test?

2021-12-06 21:07 UTC, TomJaeger commented on tests/cypress/support/templates/cats.group/archive-sorted.html
> +    {exp:channel:category_archive channel="about" style="linear" orderby="title"}
Should this be different then whats on line 2?

2021-12-06 21:08 UTC, TomJaeger reviewed
Left 2 comments for @intoeetive below. I also noticed that you made mention of adding tests around sticky above @intoeetive I think it would be good to get them in before we merge.

2021-12-17 08:25 UTC, merged