fixed JS error in ordering relationships fields, EECORE-1277
ExpressionEngine/ExpressionEngine pull request #1312
Opened 2021-08-27 12:01 UTC by Yulyaswan

the error appeared after:
1. the image has been upload into the grid field
2. were added 2 items to the relationship field 
3. were re-ordered these relationship fields

2021-10-07 09:54 UTC, intoeetive requested changes

2021-10-07 09:54 UTC, intoeetive commented on themes/ee/asset/javascript/src/jquery/ui/jquery.ui.sortable.js
> +		// this._trigger("sort", event, this._uiHash());
I am not sure this code can be commented out. I believe we have some scripts that rely on "sort" event - unless this has been checked

2021-10-21 13:34 UTC, obfuscode commented on themes/ee/asset/javascript/src/jquery/ui/jquery.ui.sortable.js
> +		// this._trigger("sort", event, this._uiHash());
This was reverted by 3b15de4. Resolving conversation.

2021-10-21 13:36 UTC, obfuscode approved these changes

2021-10-22 12:46 UTC, intoeetive approved these changes

2021-10-22 12:46 UTC, merged