Fix the model generation
ExpressionEngine/ExpressionEngine pull request #1508
Opened 2021-10-28 19:47 UTC by matthewjohns0n

EECORE-1483

This includes better examples of how to use the model in the model that is generated.

2021-10-29 05:40 UTC, intoeetive commented on system/ee/ExpressionEngine/Service/Generator/stubs/addon_model.php
> +        '{{class}}'    => 'Models\{{class}}',
I believe the common convention used by EE is `Model` folder. And this might be needed to change in other places as well

2021-10-29 05:40 UTC, intoeetive commented on system/ee/ExpressionEngine/Service/Generator/stubs/model.php
> +        return $this->first_name.' '.$this->last_name;
This is not following PSR-12 formatting (needs spaces)

2021-10-29 05:41 UTC, intoeetive requested changes
I think we need some changes here - see the comments

2021-11-10 19:23 UTC, matthewjohns0n commented on system/ee/ExpressionEngine/Service/Generator/stubs/addon_model.php
> +        '{{class}}'    => 'Models\{{class}}',
I've updated this to use the `Model` folder.

2021-11-11 06:42 UTC, intoeetive requested changes
@matthewjohns0n this worked fine, however I spotted related issue which I think would be nice to address together with this one.

I used single quote in author's name (which is not uncommon with European names) and it was used as part of namespace for model, so all code was broken. I think we need to strip everything that's not letter from the namespace

2021-12-07 22:55 UTC, matthewjohns0n commented
@intoeetive I like the suggestion of filtering the namespace. I've added that to this PR.

I don't agree with your second comment though regarding this code:

```
namespace JustMeHere\One\Model;

use ExpressionEngine\Service\Model\Model;

class Two extends Model
```

I think it is clear what the code is doing. In this example, the fully qualified name of the class is `JustMeHere\One\Model\Two` and it is using (and extending) the class `ExpressionEngine\Service\Model\Model`. There will be no conflicts here, since we are clearly using that model. 

If we wanted to be more clear for people just glancing at the code, we could change the use line to something like this:

```
namespace JustMeHere\One\Model;

use ExpressionEngine\Service\Model\Model as EEModel;

class Two extends EEModel
```

I'm happy with either solution, although this is unnecessary from an OOP point of view.

2021-12-08 08:20 UTC, intoeetive approved these changes

2021-12-10 21:21 UTC, matthewjohns0n commented
I have been looking into the tests failing and I just can't explain it. I set up cypress locally and ran all the tests on this branch and it passed all the tests. The tests that fail have absolutely nothing to do with the code I changed, so I'm convinced this is an issue with cookie consents/ the tests surrounding them. 

@intoeetive I see that you did recently change these tests and cookie-related things here:
https://github.com/ExpressionEngine/ExpressionEngine/commit/10a7091519395eb757dffc9fed9ec3826be2ed5d

The tests failing on this branch seem directly related to this. I'm not sure where else/ how far to dig. I'll try merging anything recent into this branch and pushing to retrigger the tests, but beyond that, I'm not sure how else to fix this.

2021-12-10 22:29 UTC, matthewjohns0n commented
Looks like that worked and now the tests passed! Excited to see that, I was very confused at this.

2021-12-14 20:27 UTC, obfuscode approved these changes

2021-12-14 20:27 UTC, merged