Revised main Entries screen title, EECORE-1058
ExpressionEngine/ExpressionEngine pull request #1524
Opened 2021-11-02 07:52 UTC by Yulyaswan

EECORE-1058
Removed main title block, moved the button to the white block `panel-heading `, made title statiс

2021-11-09 15:32 UTC, obfuscode commented on system/ee/ExpressionEngine/Controller/Publish/Edit.php
> +            'class' => strtolower(lang('entry_manager'))
I think this just needs to be `entries` without the call to the lang file otherwise people with language translations would end up with a different class name.

2021-11-09 15:32 UTC, obfuscode requested changes
See line comment

2021-11-09 15:51 UTC, Yulyaswan commented on system/ee/ExpressionEngine/Controller/Publish/Edit.php
> +            'class' => strtolower(lang('entry_manager'))
changed

2021-11-09 16:07 UTC, obfuscode requested changes
Added comment on jira ticket.

2021-12-06 16:06 UTC, intoeetive commented
@Yulyaswan the tests are failing. I believe they need to be updated to reflect the changes you made

2021-12-14 21:28 UTC, obfuscode approved these changes

2021-12-14 21:28 UTC, merged