added status on "All Roles" landing page, EECORE-1503
ExpressionEngine/ExpressionEngine pull request #1622
Opened 2021-12-08 08:46 UTC by Yulyaswan

fixes #1523 
EECORE-1503

2022-01-10 09:34 UTC, intoeetive requested changes
Tested, looks good functionality-wise; there's a PSR code styling fix needed however

2022-01-10 09:34 UTC, intoeetive commented on system/ee/ExpressionEngine/Controller/Members/Roles/Roles.php
> +                'status' =>($role->is_locked == 'y') ? 'locked' : 'unlocked',
This line does not seem to follow PSR-12 coding style (missing space)

2022-01-20 14:44 UTC, TomJaeger commented on system/ee/ExpressionEngine/Controller/Members/Roles/Roles.php
> +                'status' =>($role->is_locked == 'y') ? 'locked' : 'unlocked',
I think this should also be pulled from a Lang file?

2022-01-24 10:11 UTC, intoeetive approved these changes

2022-01-24 14:48 UTC, TomJaeger approved these changes

2022-01-24 14:48 UTC, merged