Add `has_children` to `exp:categories` and `exp:category_archive`
ExpressionEngine/ExpressionEngine pull request #1727
Opened 2022-01-14 19:48 UTC by robsonsobral

## Overview

Add `{has_children}` variable to `exp:categories` and `exp:category_archive`.

Resolves [##1726](https://github.com/ExpressionEngine/ExpressionEngine/issues/#1726).

## Nature of This Change

- [ ] 🐛 Fixes a bug
- [x] 🚀 Implements a new feature
- [ ] 🛁 Refactors existing code
- [ ] 💅 Fixes coding style
- [ ] ✅ Adds tests
- [ ] 👽 Adds new dependency
- [ ] 🔥 Removes unused files / code
- [ ] 🔒 Improves security 

## Is this backwards compatible?

- [x] Yes
- [ ] No

## Documentation

User Guide Pull Request: https://github.com/ExpressionEngine/ExpressionEngine-User-Guide/pull/NNN

2022-01-18 12:57 UTC, intoeetive approved these changes, later dismissed
The code looks good to me, but need documentation (and preferably tests)

2022-01-27 02:40 UTC, robsonsobral commented
Tests added in the dark, due to environment issues.

I started to test for `{if active}` too, but I got lost.

2022-01-27 13:46 UTC, robsonsobral commented
@intoeetive , I wasn't capable of setting the parent category of **category two** without seeing what I'm doing.

2022-02-01 08:13 UTC, intoeetive commented
It does not looks like tests have been written correctly. You're expecting `category one` to have children, however it does not have any

2022-02-06 01:35 UTC, robsonsobral commented
Thank you, @intoeetive . Everything is working, now.

I updated some previous tests to also consider category nesting.

2022-02-09 09:16 UTC, intoeetive requested changes
Spotted an issue in test templates.

If you still can't get Cypress running locally, I can try making that update for you

2022-02-09 09:16 UTC, intoeetive commented on tests/cypress/support/templates/cats.group/index.html
> -{exp:channel:categories channel="news" style="linear"}
Linear and nested categories use different code that generates display. This test template is specifically set to use linear mode, so please let's continue using it. And maybe we need separate test template for the nested mode.

2022-03-12 21:16 UTC, robsonsobral commented
For reviewers to keep an eye on:

- the conflicts are related to a new test being added. Could it have a better description?

2022-03-28 09:20 UTC, intoeetive reviewed
@robsonsobral the code looks good to me!

But I have question on tests - it looks like you're changing the "reorder" test to nest categories instead of reordering. Would it be better to add new test instead? Basically, keep the old and new version

2022-05-04 11:29 UTC, intoeetive commented
@robsonsobral I'm making this PR draft until conflict on tests is resolved (I still think we just need a separate test for this change, and keep the existing test for other things)

2022-05-05 02:07 UTC, robsonsobral commented
I've already move back your tests to the original state, @intoeetive , and just added mine. However, it isn't clear among all changes. I rebased this branch on the current dev. Everything is clearer now.

I gonna move my tests to their own `it()`s tomorrow (for me).

2022-05-06 01:33 UTC, robsonsobral commented
@intoeetive , the templates for tests aren't being copied to the system folder. Weird...

2022-07-03 00:51 UTC, robsonsobral commented
I've no idea why the build tools are failing!

2022-07-04 01:53 UTC, robsonsobral commented
Is there something I can do to fix the **Build EE for testing**? There's an error on `gulp`:

> Run gulp build-app --local --nogit --head --skip-lint --skip-pro --version=6.3.4
> ReferenceError: primordials is not defined

2022-08-16 13:10 UTC, intoeetive approved these changes

2022-08-16 13:10 UTC, merged