Add `show_date_span` parameter to channel calendar
ExpressionEngine/ExpressionEngine pull request #174
Opened 2019-04-12 21:02 UTC by imacrayon

## Overview

Added a `show_date_span="yes"` parameter to the `{exp:channel:calendar}` tag which repeats the entry across every calendar "day" cell between the entry’s publish and expiration date.

Given an entry (My Event) with and `entry_date` of **April 1, 2019** and an `expiration_date` of **April 5, 2019** - enabling `show_date_span="yes"` would display an calendar with the first week like this:

| S  | M | T | W | T | F | S |
| :-- | :-- | :-- | :-- | :-- | :-- | :-- |
| 31<br>&nbsp; | 1<br>My Event | 2<br>My Event | 3<br>My Event | 4<br>My Event | 5<br>My Event  | 6<br>&nbsp; |

Entires without an `expiration_date` will continue to show on a single day.

When combine with `show_future_entries="yes"`, this would be useful for anyone wanting to build a simple event calendar.

## Nature of This Change

- [ ] 🐛 Fixes a bug
- [x] 🚀 Implements a new feature
- [ ] 🛁 Refactors existing code
- [ ] 💅 Fixes coding style
- [ ] ✅ Adds tests
- [ ] 👽 Adds new dependency
- [ ] 🔥 Removes unused files / code
- [ ] 🔒 Improves security 

## Is this backwards compatible?

- [x] Yes
- [ ] No

## Documentation
Coming soon...

2019-08-08 20:17 UTC, derekjones requested changes

2019-08-08 20:17 UTC, derekjones commented on system/ee/EllisLab/Addons/channel/mod.channel.php
> +                    if (filter_var(ee()->TMPL->fetch_param('show_expired'), FILTER_VALIDATE_BOOLEAN))
[get_bool_from_string()](https://github.com/ExpressionEngine/ExpressionEngine/blob/ea47b5f94d4b8e6b2c898af1a856a278c03fc807/system/ee/EllisLab/ExpressionEngine/Boot/boot.common.php#L308) can help here, and eliminate the need for `filter_var()`

2019-08-08 20:17 UTC, derekjones commented on system/ee/EllisLab/Addons/channel/mod.channel_calendar.php
> +                    if (filter_var(ee()->TMPL->fetch_param('show_date_span'), FILTER_VALIDATE_BOOLEAN) && $row['expiration_date'])
See above comment regarding `get_bool_from_string()`

2021-03-30 15:27 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ExpressionEngine/ExpressionEngine?pullRequest=174) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ExpressionEngine/ExpressionEngine?pullRequest=174) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ExpressionEngine/ExpressionEngine?pullRequest=174) it.</sub>

2021-07-16 07:37 UTC, intoeetive commented
@imacrayon thank you for this contribution!

Since EE5 is only receiving security updates at this point, would you be willing to update this PR for EE6, make it to be against `6.dev` and also sign our updated contributor license agreement?

2026-05-26 15:05 UTC, closed without merging