Patch/wrong validation of category fields
ExpressionEngine/ExpressionEngine pull request #1892
Opened 2022-03-12 19:25 UTC by robsonsobral

Followup of #1672

## Overview

When creating a category field, the validation of its name checks against previously created fields of the entire site, instead of the same category group only.

Resolves [#1277](https://github.com/ExpressionEngine/ExpressionEngine/issues/1277).

## Nature of This Change

- [x] 🐛 Fixes a bug
- [ ] 🚀 Implements a new feature
- [ ] 🛁 Refactors existing code
- [ ] 💅 Fixes coding style
- [ ] ✅ Adds tests
- [ ] 👽 Adds new dependency
- [ ] 🔥 Removes unused files / code
- [ ] 🔒 Improves security 

## Is this backwards compatible?

- [x] Yes
- [ ] No

2022-03-12 19:30 UTC, robsonsobral commented
For reviewers to keep an eye on:

- Is to edit the same code in 5 places of a file a sign it's time to refactor?
- I had to add a ternary to avoid a PHP deprecation warning on `FieldModel.php`;
- @robinsowell is finding bugs on my PRs because she's jealous I live in a warmer country than hers!

2022-05-04 11:06 UTC, intoeetive requested changes
Thought the original PR https://github.com/ExpressionEngine/ExpressionEngine/pull/1672 was merged, it has been reverted afterwards because of the bug Robin has found.

@robsonsobral if you still want to work on this, the changes from original PR need to be present here

I'm marking it as draft for now

2022-07-04 12:15 UTC, robsonsobral commented
I rebased this branch on the current 6dev. I still can write some tests. While that, don't you want to embaress me again, @robinsowell ?

2023-01-18 22:56 UTC, robsonsobral commented
@intoeetive , can we, please, move on with this?

2023-01-19 06:46 UTC, intoeetive commented
@robsonsobral I think based on comment from @robinsowell there's an issue with that code (that you PRed separately) https://github.com/ExpressionEngine/ExpressionEngine/pull/1672#issuecomment-1047992645

Can you just confirm that the other changes in this PR are taking care of that?

2023-01-20 21:58 UTC, robsonsobral commented
Sure, boss! I can take a look at that. Is to have categories with the same name on different groups still forbidden?

2023-01-23 13:51 UTC, intoeetive commented
Yes - I believe issues reported by Robin on other PR would be still relevant

2025-12-03 20:42 UTC, TomJaeger commented
Closing as this was addressed via other PR mentioned in the thread.

2025-12-03 20:42 UTC, closed without merging