Support for RTL languages
ExpressionEngine/ExpressionEngine pull request #1929
Opened 2022-03-26 01:22 UTC by nawafinity

## Overview

I've been using ExpiressionEngine before it became open source, I really like it, and as an Arabic speaker I've been waiting for support for RTL languages for a long time and have recently been working on the Arabic language package and during that I decided to do the work needed to support RTL languages.

In this PR, I did the following:
1. I used the [rtlcss](https://github.com/MohammadYounes/rtlcss) library to make a right-to-left version of the control panel styles. (The library is used by Bootstrap and Netflix and many projects).
2. I have added a new method in `Lang.php` that helps to get the language direction.
3. I added two new scripts on `package.json` 
	- `rtl:css` Which you can use after `build:css` to create an RTL version of cp-styles.
	- `rtl:demo-css` Which you can use to create RTL version of user/site/default styles.
4. I added a new view global variable "lang_dir" which can be used <html dir="{lang_dir"}> and also modified the variable {lang}.
5. Both view variables {lang} and {lang_dir} are now conditional variables so user can do something like:
![image](https://user-images.githubusercontent.com/50952092/160219024-aa8f6f9a-3519-4093-a3f5-e49a45679bc7.png)
6. I also modified Jump Menu script to support RTL.

Hope I did everything right.

![image](https://user-images.githubusercontent.com/50952092/160219097-7aeaf2f6-7e44-44a4-b2ad-7e645558497c.png)

Resolves [#844](https://github.com/ExpressionEngine/ExpressionEngine/issues/844).

## Nature of This Change

- [ ] 🐛 Fixes a bug
- [x] 🚀 Implements a new feature
- [x] 🛁 Refactors existing code
- [ ] 💅 Fixes coding style
- [ ] ✅ Adds tests
- [x] 👽 Adds new dependency
- [ ] 🔥 Removes unused files / code
- [ ] 🔒 Improves security 

## Is this backwards compatible?

- [x] Yes
- [ ] No

## Documentation

User Guide Pull Request: https://github.com/ExpressionEngine/ExpressionEngine-User-Guide/pull/NNN

2022-03-26 01:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ExpressionEngine/ExpressionEngine?pullRequest=1929) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ExpressionEngine/ExpressionEngine?pullRequest=1929) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ExpressionEngine/ExpressionEngine?pullRequest=1929) it.</sub>

2022-03-29 06:31 UTC, intoeetive commented
Hello @nawafinity and thank you for your contribution.

This looks pretty solid already. We'll give it some more testing and then approve. Thanks!

2022-03-29 22:48 UTC, nawafinity commented
> Hello @nawafinity and thank you for your contribution.
> 
> This looks pretty solid already. We'll give it some more testing and then approve. Thanks!

Hello @intoeetive ,
I am glad that you are satisfied with the work.
I'm currently working on getting ExpressionEngine to support languages other than English in creating slugs.

![chrome-capture-2022-2-30](https://user-images.githubusercontent.com/50952092/160718360-fed18c13-1988-4946-ba07-ec2408d3144f.gif)

| Language | Support |
|--|--|
| Arabic | ✅ |
| Latin | ✅ |
| Greek | ✅ |
| Turkish | ✅ |
| Russian | ✅ |
| Ukranian (💖)| ✅ |
| Czech | ✅ |
| Polish | ✅ |
| Latvian | ✅ |
| Armenian | ✅ |

2022-04-11 07:52 UTC, intoeetive commented
@nawafinity is Arabic language pack for EE available for download somewhere? If not, can you send it to us? (even if it's incomplete, just for the testing purposes)

2022-05-14 22:47 UTC, nawafinity commented
Hello @intoeetive, sorry for the late reply, I was I've been very sick lately, you can find in the attachments the incomplete Arabic language pack.
[arabic.zip](https://github.com/ExpressionEngine/ExpressionEngine/files/8694000/arabic.zip)

Right now I'm facing a problem with Popperjs it does not support RTL so I'm trying to upgrade it to version 2 or find a way to make it work with RTL layout.

2022-08-16 14:24 UTC, intoeetive requested changes
@nawafinity sorry it took so long to do the in-depth review - everyone was busy getting EE7 out.

I've spotted few issues which I think need to be solved before we can merge this in:

1. The built-in fields (such as title, url_title, entry dates etc) are currently forced as LTR. I think it's reasonable for title and url_title to follow the language direction, but I'm not sure about the date fields?

2. It looks like the dropdown for entry status does not work when I switch the CP to Arabic (the other dropdowns

3. Looks like we need a way to force the LTR text direction for the specific fields. Currently in settings URL fields look like `/http://ee6.local` which is obviously not correct

4. I don't think specifying the character map for URL title generation directly in JS file is the way to go. We have dedicated config file to store the mapping: https://docs.expressionengine.com/latest/config/config-files.html#foreign-characters
But I also not 100% sure we need to overload it with the full map for all languages... maybe that's something that could be done as part of language pack... not sure.  Just noting this need to be handled in more "generic" way

5. I also see stuff in the JS that is a) specific to just Arabic language and b) specific to your needs maybe? Like making URL titles support Arabic - I would assume not everyone would want that. So at the minimum, that needs to be configurable.

All in all, this seems to be more complex than it seemed initially.

I feel like # 1, 4, and 5 could be skipped from the PR, but the # 2 and 3 need to solved at the minimum.

I'll make the PR draft for now.

If you are not able / willing to contribute into this more currently, maybe you could just provide some ideas on the path to go, because out in-house experience with the RTL languages is quite limited.

Thank you

2022-11-17 05:52 UTC, mustafa-online commented
Hope this get merged soon :)

2025-12-03 20:46 UTC, TomJaeger commented
Closing this PR as it's very out of date.

Looks like you did some really great work on this.  If you are interested in updating it and opening the PR against 7.dev we would love to see this addition!

2025-12-03 20:46 UTC, closed without merging