hide global field settings for notes, EECORE-1795
ExpressionEngine/ExpressionEngine pull request #1984
Opened 2022-04-07 11:32 UTC by Yulyaswan

2022-04-12 08:56 UTC, intoeetive requested changes
I think "include in search" and "hide field" toggles should also be hidden here.

Also there's high chance that once implemented we'll need similar changes for other fields (e.g. remove "include in search" from relationship fields). So probable makes sense to have this script in a file that's always included on Fields controller, not specific `notes.js`

2022-04-13 22:14 UTC, matthewjohns0n commented
This is definitely moving in the right direction. I do think we should allow add-ons to define what fields to hide though, that way any add-on could use this feature by defining some sort of "hide settings" array.

2022-04-27 14:00 UTC, intoeetive approved these changes
I think it's good for now. We can improve it later on

2022-04-27 14:07 UTC, matthewjohns0n approved these changes

2022-04-27 14:20 UTC, merged