backup database views
ExpressionEngine/ExpressionEngine pull request #2064
Opened 2022-05-04 13:01 UTC by CreepCaster

## Overview

Fix backup for database views - previously it throws exception, because "CREATE TABLE" for "view" structure is incorrect.
https://dev.mysql.com/doc/refman/8.0/en/show-table-status.html

> For views, most columns displayed by [SHOW TABLE STATUS](https://dev.mysql.com/doc/refman/8.0/en/show-table-status.html) are 0 or NULL except that Name indicates the view name, Create_time indicates the creation time, and **Comment says VIEW**

## Nature of This Change

- [x] 🐛 Fixes a bug
- [ ] 🚀 Implements a new feature
- [ ] 🛁 Refactors existing code
- [ ] 💅 Fixes coding style
- [ ] ✅ Adds tests
- [ ] 👽 Adds new dependency
- [ ] 🔥 Removes unused files / code
- [ ] 🔒 Improves security 

## Is this backwards compatible?

- [x] Yes
- [ ] No

2022-05-04 13:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ExpressionEngine/ExpressionEngine?pullRequest=2064) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ExpressionEngine/ExpressionEngine?pullRequest=2064) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ExpressionEngine/ExpressionEngine?pullRequest=2064) it.</sub>

2022-08-16 06:28 UTC, intoeetive requested changes
Hi @CreepCaster ,

thank you for your contribution - and sorry for late reaction.

I think the code is good addition - even though EE does not use MySQL views internally, the add-ons or custom site setups can use those.
However, it looks like the change from `$this->getTables();` to `$this->query->getTables();` is making `setTablesToBackup()` function impossible to use (and thus making CMS-specific backups not possible)

Is that something you'd be willing to look into more?

2022-08-27 05:44 UTC, CreepCaster commented
Hi @intoeetive ,
thank you for review. Really my bad, fixed.

2022-09-06 12:30 UTC, intoeetive approved these changes

2022-09-06 12:32 UTC, intoeetive commented
Reviewed the code and tested - looks good and works well. Approving.

@CreepCaster would you mind creating another PR from same branch into `7.dev` (for ExpressionEngine 7)?

2022-10-24 12:39 UTC, bryannielsen approved these changes

2022-10-24 13:21 UTC, merged