Resolved issue where PHP notice could be shown when calling Template library from an add-on
ExpressionEngine/ExpressionEngine pull request #2111
Opened 2022-06-15 14:29 UTC by jcogs-design

Line 1779 of `ee/legacy/libraries/Template.php` is passing null to `str_replace` under some conditions and assuming null will be replaced by ''.  php 8.1 doesn't like this and issues a deprecation warning. This uses the null coalescing operator to replace null with '' when the function is called if necessary.

## Overview

Replace this paragraph with a description of your changes and reasoning. Provide links to external references/discussions if appropriate.

Resolves [#NN](https://github.com/ExpressionEngine/ExpressionEngine/issues/NN).

## Nature of This Change

- [ ] 🐛 Fixes a bug
- [ ] 🚀 Implements a new feature
- [ ] 🛁 Refactors existing code
- [ ] 💅 Fixes coding style
- [ ] ✅ Adds tests
- [ ] 👽 Adds new dependency
- [ ] 🔥 Removes unused files / code
- [ ] 🔒 Improves security 

## Is this backwards compatible?

- [ ] Yes
- [ ] No

## Documentation

User Guide Pull Request: https://github.com/ExpressionEngine/ExpressionEngine-User-Guide/pull/NNN

2022-08-10 14:11 UTC, intoeetive requested changes
Unfortunately `??` operator is not available in PHP 5.6 (and EE6 still supports that)

How about typecasting on line 1793, `$return_data = (string) $EE->$meth_name();` - would that solve the issue? (I'm assuming `null` in this case is coming from an add-on?)

2022-08-10 14:30 UTC, jcogs-design commented
Have updated patch to use suggested alternative php5.6 compatible solution.

2022-08-10 14:36 UTC, intoeetive approved these changes

2022-08-15 12:54 UTC, bryannielsen approved these changes

2022-08-15 14:32 UTC, merged