Changed hardcoded "of" to proper language string
ExpressionEngine/ExpressionEngine pull request #2376
Opened 2022-09-07 06:12 UTC by igreil

## Overview

In system/ee/ExpressionEngine/Service/Profiler/Section/Performance.php, line 56, the word "of" is hardcoded. You'll only notice when using a language pack, where it should be translated to, say, "de" in French or "von" in German, but is not.

## Nature of This Change

Simply use `lang('of')` which uses the correct string from the language files.

- [X] 🐛 Fixes a bug
- [ ] 🚀 Implements a new feature
- [ ] 🛁 Refactors existing code
- [ ] 💅 Fixes coding style
- [ ] ✅ Adds tests
- [ ] 👽 Adds new dependency
- [ ] 🔥 Removes unused files / code
- [ ] 🔒 Improves security

## Is this backwards compatible?

- [X] Yes
- [ ] No

2022-09-07 06:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ExpressionEngine/ExpressionEngine?pullRequest=2376) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ExpressionEngine/ExpressionEngine?pullRequest=2376) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ExpressionEngine/ExpressionEngine?pullRequest=2376) it.</sub>

2022-09-08 13:18 UTC, intoeetive requested changes
@igreil just realized you missed an extra space that's needed before 'of' - can you add that?

2022-09-08 13:42 UTC, igreil commented
I'm not sure it's actually needed (it worked fine for me without), but sure: I added a space before "of".

2022-09-08 13:45 UTC, intoeetive approved these changes

2022-09-09 14:38 UTC, merged