Deprecation Resolution for PHP 8.1.6 When Getting Column Details
ExpressionEngine/ExpressionEngine pull request #2598
Opened 2022-12-04 07:25 UTC by projectnoontide

Deprecated: Automatic conversion of false to array is deprecated

2022-12-04 07:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ExpressionEngine/ExpressionEngine?pullRequest=2598) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ExpressionEngine/ExpressionEngine?pullRequest=2598) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ExpressionEngine/ExpressionEngine?pullRequest=2598) it.</sub>

2023-01-06 18:58 UTC, matthewjohns0n requested changes

2023-01-06 18:58 UTC, matthewjohns0n commented on system/ee/ExpressionEngine/Addons/pro_search/libraries/Pro_search_fields.php
> +                $cols[$field_id] = [];
Looks like if `$cols` is an array arleady, but `$cols[$field_id]` is not set, then `$cols[$field_id] = []` will not get set. I think if you move the `$cols[$field_id] = [];` assignment after the `if` block it should be good to include.

2023-01-13 23:16 UTC, matthewjohns0n approved these changes, later dismissed

2023-02-02 06:11 UTC, intoeetive approved these changes

2023-02-02 06:34 UTC, merged