Update ft.colorpicker.php to name a color
ExpressionEngine/ExpressionEngine pull request #2634
Opened 2022-12-12 18:26 UTC by litzinger

## Overview

Color picker is great, but the hex color value doesn't jive well with site css. Usually colors or themes are given a name and assigned through a class instead of relying on `<div style="color: {colorpicker_field}">` this change provides an optional Name field so we use `div class="my-thing__{colorpicker_field:name}">` instead.

- [ ] 🐛 Fixes a bug
- [x] 🚀 Implements a new feature
- [x] 🛁 Refactors existing code
- [ ] 💅 Fixes coding style
- [ ] ✅ Adds tests
- [ ] 👽 Adds new dependency
- [ ] 🔥 Removes unused files / code
- [ ] 🔒 Improves security 

## Is this backwards compatible?

- [x] Yes
- [ ] No

## Documentation
If this gets approved in this form or some form I'll update the docs

2022-12-12 18:27 UTC, litzinger commented
<img width="170" alt="Screenshot 2022-12-12 at 10 26 55 AM" src="https://user-images.githubusercontent.com/53965/207124837-6d2b9d3a-7066-425e-bf29-9807bc343e8e.png">
<img width="1336" alt="Screenshot 2022-12-12 at 10 12 35 AM" src="https://user-images.githubusercontent.com/53965/207124840-dd0cc2de-4ae0-4163-bb18-81476246841c.png">

2022-12-13 11:08 UTC, intoeetive requested changes
@litzinger thank you for submission!

Found an issue with it though - if you have several swatches with color and name, and then you add a swatch and don't provide name for it - it would duplicate the name of the previous swatch. 

Also it would be good to have headers for the columns (like the dropdown field options have) because it's not 100% clear what should go into second column once the placeholder is not there (for existing rows)

2022-12-13 15:53 UTC, litzinger commented
Good points. The headers though do not align vertically with the columns when using the MiniGrid field... they haven't for quite awhile, so I opted to use the placeholder text.

I'll take a look at the duplication issue when I find some time.

2023-01-04 20:45 UTC, litzinger commented
I made a small update based on the changes you suggested.
<img width="1021" alt="Screenshot 2023-01-04 at 2 22 08 PM" src="https://user-images.githubusercontent.com/53965/210646350-8cc885f6-25f5-41d5-953c-a77be0250e2c.png">

This one intentionally should have no color in the 3rd row and 2 empty name values after I tested adding additional rows and also sorting them and then saving the field settings.
<img width="1497" alt="Screenshot 2023-01-04 at 2 43 46 PM" src="https://user-images.githubusercontent.com/53965/210646384-d62ad68a-67c6-4393-9211-0578f8c21f31.png">

2023-01-05 08:00 UTC, intoeetive commented
@litzinger this does not seem to have issues I noticed before, so I think we're good about including it. Thank you!

@Yulyaswan can you just test this once again and if possible provide better alignment for 'Name' heading on Swatches table?

2023-01-05 10:41 UTC, Yulyaswan approved these changes

2023-01-05 13:58 UTC, litzinger commented
I took a look at the alignment thing and I think it'll involve moving the div that contains the headers inside of the `field-control` div, and only printing the header on the first row. I almost had this completed but decided to undo the changes b/c it felt like a separate unit of work, thus a separate PR. I don't know if there is any CSS Grid/Flexbox magic that could do it better though.

2023-01-05 14:07 UTC, intoeetive approved these changes

2023-01-09 12:11 UTC, merged