Member management form class
ExpressionEngine/ExpressionEngine pull request #2659
Opened 2022-12-20 19:44 UTC by jHards

## Overview

Makes Member Management front-end forms more consistent, per feature request. {exp:member:edit_profile} is hardcoding the form ID = "cform" and this has been left as-is; otherwise all form tags referenced can now accept form_class, form_name and form_id.

Resolves [#2658](https://github.com/ExpressionEngine/ExpressionEngine/issues/2658).

## Nature of This Change

- [ ] 🐛 Fixes a bug
- [x] 🚀 Implements a new feature
- [ ] 🛁 Refactors existing code
- [ ] 💅 Fixes coding style
- [ ] ✅ Adds tests
- [ ] 👽 Adds new dependency
- [ ] 🔥 Removes unused files / code
- [ ] 🔒 Improves security 

## Is this backwards compatible?

- [x] Yes
- [ ] No

2022-12-28 10:41 UTC, intoeetive requested changes
Thank you!

Perhaps you could do just one more small code style change, see the other comment

2022-12-28 10:41 UTC, intoeetive commented on system/ee/ExpressionEngine/Addons/member/mod.member_settings.php
> +                'ACT' => ee()->functions->fetch_action_id('Member', 'update_profile'));
The closing parenthesis for `array()` needs to go into new line, otherwise I think we're good here

2023-01-04 16:15 UTC, TomJaeger commented
Set this for 7.2.x... Just noting that we also need to update docs for this.

2023-01-05 12:36 UTC, intoeetive approved these changes

2023-01-09 12:07 UTC, merged