Resolved #4185 where the page scrolled up when the file field modal window was opened
ExpressionEngine/ExpressionEngine pull request #4195
Opened 2024-04-03 12:57 UTC by Yulyaswan

Resolved #4185 where the page scrolled up when the file field modal window was opened

2024-04-04 20:07 UTC, bryannielsen commented
I think this fixes the behavior of bringing the scroll back to the field you were editing but when I try to choose an image I can no longer scroll within the modal for selecting an image further down in my upload location.  If I switch back to 7.dev it appears to work again.

2024-04-09 14:04 UTC, bryannielsen requested changes
Now I'm having issues scrolling back to the top of the file modal.  I can't see the top of my files list or the search/filter bars in the file modal and I can't scroll at all.

My setup is a file field down at the bottom of the channel entry publish screen and a long list of files in my upload location.  I'm also making my window fairly narrow to make the scroll area bigger.

2024-07-09 12:24 UTC, Yulyaswan commented
I can't reproduce this

2025-02-20 19:30 UTC, robinsowell approved these changes
This definitely fixed it form me in a test- though granted, quirky one to test.  But I could duplicate before dropping in the fix, so I think it looks good.

2025-04-29 18:30 UTC, bryannielsen approved these changes

2025-05-01 18:01 UTC, merged