fixed spacing in Spam dashboard widget where number of trapped comments was on top of text
ExpressionEngine/ExpressionEngine pull request #958
Opened 2021-03-24 15:15 UTC by ops-andy

## Overview
fixed spacing in Spam dashboard widget where number of trapped comments was on top of text

## Nature of This Change

- [ ] 🐛 Fixes a bug
- [ ] 🚀 Implements a new feature
- [x] 🛁 Refactors existing code
- [ ] 💅 Fixes coding style
- [ ] ✅ Adds tests
- [ ] 👽 Adds new dependency
- [ ] 🔥 Removes unused files / code
- [ ] 🔒 Improves security

2021-03-24 15:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ExpressionEngine/ExpressionEngine?pullRequest=958) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ExpressionEngine/ExpressionEngine?pullRequest=958) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ExpressionEngine/ExpressionEngine?pullRequest=958) it.</sub>

2021-04-05 13:42 UTC, intoeetive requested changes

2021-04-05 13:42 UTC, intoeetive commented on system/ee/ExpressionEngine/View/_shared/dashboard/dashboard.php
> +			<b class="ml-s"><?=$trapped->total_trapped?></b>&nbsp; <?=lang($trapped->content_type)?><?php if ($trapped->total_trapped > 1):?>s<?php endif ?> marked as <?=lang('spam')?>
"marked as" needs to be moved to lang file

2021-05-26 18:34 UTC, obfuscode commented
@ops-andy Can you extract the "marked as" text to the language file. It also looks like one of the tests is failing but that may be a faulty run. We can take a look again after the language file update if it's still failing.

2021-05-26 21:16 UTC, ops-andy commented
@obfuscode updated to fix both plural issue and moving 'marked_as'

2021-05-27 12:20 UTC, ops-andy commented
@obfuscode once again I'm getting timeout with the removing variable step in the tests. Since my code doesn't touch that, I think this should be good to go.

2021-05-28 12:22 UTC, obfuscode approved these changes

2021-05-28 12:22 UTC, merged